### ISSUE TITLE
Номер журнала?

### ISSUE THREAD

**Issue by nyukers** [zaryava/contact_v.4#1]
В каком номере журнала "Системный администратор" описание разработки вашей программы «Контакты» с **Web-интерфейсом**?

**Comment by zaryava** [comment]
Статья с описанием начала разработки программы «Контакты» с
Web-интерфейсом была
подготовлена и отправлена главному редактору журнала для публикации в
октябрьском номере, но со мной никто не связался и статья опубликована не
была. По какой причине мне не известно.

вт, 30 нояб. 2021 г. в 11:37, Nyukers ***@***.***>:

**Comment by nyukers** [comment]
Будет печально если такой материал ляжет в стол.
